name = "MySecondPackage"
uuid = "8418302f-bbdc-483a-a474-0ec4cbdaf7eb"
authors = ["Promia Chowdhury <promia@mit.edu> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
